import assert from 'node:assert/strict';
import { htmlToLines, splitQuestions } from '../lib/parser';

const parse = (lines: string[]) => splitQuestions(lines, '七年级', 'edge-cases.docx');
const prefixed = parse(['一、单项选择', '（　）1. What is it?A. One B. Two', '( ) 2. Choose one.', 'A. yes', 'B. no', '参考答案与解析', '1. B 2. A']);
assert.deepEqual(prefixed.questions.map(q => [q.originalNo,q.answer,q.options.length]), [['1','B',2],['2','A',2]]);
assert.equal(prefixed.questions[0].stem, 'What is it?');
const full = parse(['一、书面表达','21. Write about a friend.','要求：1. About sixty words.','2. Include all points.','3. Use no real names.','答案与解析：','21. 【高分范文】','First paragraph.','Second paragraph.']);
assert.equal(full.questions.length,1);
assert.match(full.questions[0].stem,/3\. Use no real names/);
assert.match(full.questions[0].answer,/Second paragraph/);
const twoEssays = parse(['一、书面表达','61. Write about a friend.','要求：1. About sixty words.','2. Include all points.','62. Write about your school.','要求：1. Be clear.']);
assert.deepEqual(twoEssays.questions.map(q=>q.originalNo),['61','62']);
const gaps = parse(['一、短文填空','We 51.______ here.','They 52.______ too.','参考答案','51. are','52. are','53. missing']);
assert.deepEqual(gaps.questions.map(q => q.originalNo),['51','52']);
assert.deepEqual(gaps.report.unmatchedAnswers,['53']);
assert.match(gaps.warnings.join(' '),/不会依据答案凭空生成/);
const duplicate = parse(['一、单项选择','1. First','A. yes B. no','二、单项选择','1. Second','A. yes B. no','参考答案','1. A','1. B']);
assert.ok(duplicate.questions.every(q => !q.answer));
assert.deepEqual(duplicate.report.duplicateNumbers,['1']);
const explanation = parse(['1. First','2. Second','参考答案','1. A','【解析】Line one.','More explanation.','2. B','【解析】Line two.']);
assert.equal(explanation.questions[0].analysis,'Line one.\nMore explanation.');
assert.equal(explanation.questions[1].analysis,'Line two.');
const sparse = parse(['1. First','3. Third','参考答案','1. A','2. B','3. C']);
assert.deepEqual(sparse.report.missingNumbers,['2']);
assert.deepEqual(sparse.report.unmatchedAnswers,['2']);
const lists = htmlToLines('<ol start="16"><li>One</li><li>Two<ol><li>Subitem</li></ol></li><li value="20">Three</li></ol><ul><li>Bullet</li></ul><p><u>underlined</u></p>');
assert.deepEqual(lists,['16. One','17. Two','1. Subitem','20. Three','• Bullet','【画线：underlined】']);
const images = parse(['一、阅读理解','A','A passage','(1) Choose','A.','[[IMAGE:/api/workspace/media/test/a.png]]','B.','[[IMAGE:/api/workspace/media/test/b.png]]','参考答案','1. B']);
assert.equal(images.questions.length,1);
assert.deepEqual(images.questions[0].imageLabels,['选项 A 配图','选项 B 配图']);
assert.equal(images.questions[0].options.length,2);
const underlined = parse(['一、任务型阅读','We 【画线：love school】.','1. Translate the underlined sentence.','参考答案','1. 我们热爱学校。']);
assert.ok(!underlined.questions[0].warnings.length);
const passages = parse(['一、阅读理解','A.','Passage one','1. First','A. yes B. no','B.','Passage two','2. Second','A. yes B. no']);
assert.equal(passages.questions[0].material,'Passage one');
assert.equal(passages.questions[1].material,'Passage two');
const unsupported = parse(['1. Picture','[[IMAGE:unsupported-image]]']);
assert.deepEqual(unsupported.questions[0].images,[]);
assert.match(unsupported.questions[0].warnings.join(' '),/配图未能读取/);
assert.throws(() => parse(Array.from({length:201},(_,i)=>`${i+1}. Test`)),/200/);
console.log('PASS: parser-v2 regression cases, including prefix variants, embedded gaps, missing-question diagnostics, repeated numbers, full essay, multiline analyses, list starts/nesting, option images, punctuated passage headings, underlines and size limit.');
