import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { splitQuestions, htmlToLines, inspectZip } from '../lib/parser';
import { TEMPLATE_LINES, buildPaperDocument } from '../lib/export-docx';
import mammoth from 'mammoth';
import { Packer } from 'docx';
const sample = splitQuestions(TEMPLATE_LINES, '七年级', 'sample.docx');
assert.equal(sample.questions.length, 6);
assert.equal(sample.questions[0].answer, 'B');
assert.equal(sample.questions[2].answer, 'playing');
assert.equal(sample.questions[0].options.length, 4);
assert.equal(sample.questions[3].material, sample.questions[4].material);
assert.match(sample.questions[3].material, /Lucy/);
assert.equal(sample.questions[5].type, '书面表达');
const duplicate = splitQuestions(['一、单项选择', '1. First', 'A. a B. b', '二、单项选择', '1. Second', 'A. a B. b', '参考答案', '1. A'], '八年级', 'repeat.docx');
assert.equal(duplicate.questions[0].answer, '');
assert.equal(duplicate.questions[1].answer, '');
assert.equal(splitQuestions(['One unnumbered question'], '九年级', 'plain.docx').questions.length, 1);
assert.equal(splitQuestions(['1. A question without answer'], '七年级', 'missing.docx').questions[0].answer, '');
assert.throws(() => inspectZip(new Uint8Array(30)), /有效/);
const image = splitQuestions(['三、阅读理解', '[[IMAGE:/api/workspace/media/test/pic.png]]', 'A passage', '1. Question', 'A. yes B. no'], '七年级', 'picture.docx');
assert.equal(image.questions[0].images.length, 1);
const range = splitQuestions(['1. One', '2. Two', '参考答案', '1-2 AB'], '七年级', 'range.docx');
assert.deepEqual(range.questions.map(x => x.answer), ['A', 'B']);
assert.equal(htmlToLines('<p>1. A &amp; B</p><p>A. Yes<br/>B. No</p>')[0], '1. A & B');
const inline = splitQuestions(['1. Choose one. A. yes B. no', '【答案】A', '【解析】Sample explanation'], '七年级', 'inline.docx');
assert.equal(inline.questions[0].answer, 'A');
assert.equal(inline.questions[0].options.length, 2);
const imageOnly = splitQuestions(['[[IMAGE:/api/workspace/media/test/photo.png]]'], '七年级', 'scan.docx');
assert.equal(imageOnly.questions[0].images.length, 1);
assert.match(imageOnly.questions[0].stem, /图片题/);
const paper = { id: 'test', title: '七年级英语课堂练习', grade: '七年级' as const, minutes: 45, items: sample.questions.map(q => ({ question: q, score: 2 })) };
const student = await Packer.toBuffer(await buildPaperDocument(paper, false));
const teacher = await Packer.toBuffer(await buildPaperDocument(paper, true));
const studentText = (await mammoth.extractRawText({ buffer: student })).value;
const teacherText = (await mammoth.extractRawText({ buffer: teacher })).value;
assert.ok(!studentText.includes('参考答案与解析'));
assert.match(teacherText, /参考答案与解析/);
assert.equal((studentText.match(/Lucy is a student/g) || []).length, 1);
assert.match(teacherText, /playing/);
inspectZip(new Uint8Array(student));
console.log('PASS: template extraction, options, answer mapping, repeated-number safety, shared passages and images, missing-answer safety, malformed ZIP, ranged answers, DOCX student/teacher exports.');
