import assert from 'node:assert/strict';
import { readFileSync, mkdirSync, writeFileSync } from 'node:fs';
import { Packer } from 'docx';
import mammoth from 'mammoth';
import { blankQuestion, type Paper, type PaperItem, type State } from '../lib/model';
import { buildQuestionUnits, filterQuestionUnits, buildPaperUnits, unitSelection, toggleQuestionUnit, removePaperUnit, movePaperUnit, renumberReferences } from '../lib/question-units';
import { buildPaperDocument } from '../lib/export-docx';

const material = 'Tom is 16 years old. In 2016 he paid 16.50 yuan.\n' + Array.from({ length: 10 }, (_, i) => `Word ${i + 16}.______`).join(' ');
const questions = Array.from({ length: 10 }, (_, i) => ({ ...blankQuestion(), id: `q-${i + 16}`, sourceId: 'source-a', source: 'A.docx', type: '完形填空' as const, originalNo: String(i + 16), material,
    stem: `第 ${i + 16} 空（见共用材料）`, options: ['A. first', 'B. second', 'C. third', 'D. fourth'], answer: 'ABCD'[i % 4], knowledge: i ? ['完形填空'] : ['名词'], images: ['/api/workspace/media/source-a/shared.png'], imageLabels: ['共用材料配图'] }));
const original = JSON.stringify(questions);
const [unit] = buildQuestionUnits(questions);
assert.equal(unit.questions.length, 10);
assert.equal(unit.sharedImages.length, 1);
assert.ok(unit.display.every(q => q.images.length === 0));
assert.deepEqual(unit.display.map(q => q.stem), Array.from({ length: 10 }, (_, i) => `第 ${i + 1} 空（见共用材料）`));
assert.match(unit.material, /Word 1\._+/);
assert.match(unit.material, /Word 10\._+/);
assert.doesNotMatch(unit.material, /(?:16|25)\._+/);
assert.match(unit.material, /16 years old.*2016.*16\.50/);
assert.equal(JSON.stringify(questions), original);
assert.deepEqual(unit.numberingIssues, []);
const filtered = filterQuestionUnits([unit], { grade: '全部年级', type: '全部题型', knowledge: '名词', search: '第 16 空' });
assert.equal(filtered.length, 1); assert.equal(filtered[0].questions.length, 10);
assert.equal(filterQuestionUnits([unit], { grade: '全部年级', type: '全部题型', knowledge: '名词', search: '第 1 空' })[0].questions.length, 10);
const foreign = questions.map(q => ({ ...q, id: `other-${q.id}`, sourceId: 'source-b' }));
assert.equal(buildQuestionUnits([...questions, ...foreign]).length, 2);
assert.equal(buildQuestionUnits([...questions, { ...questions[0], id: 'grade', grade: '八年级' }, { ...questions[0], id: 'type', type: '短文填空' }]).length, 3);
const remap = new Map([['16', '1'], ['17', '2'], ['18', '3']]);
assert.equal(renumberReferences('16.__ （17）____ __18__ 第16空 第16至18小题 第16段 Question 17 Paragraph 17 16 years 2016 16.50', remap), '1.__ （2）____ __3__ 第1空 第1至3小题 第16段 Question 2 Paragraph 17 16 years 2016 16.50');
assert.equal(renumberReferences('1.__ 2.__', new Map([['1', '2'], ['2', '1']])), '2.__ 1.__');
assert.equal(renumberReferences('2016.__', remap), '2016.__');
let selected = toggleQuestionUnit([], unit);
assert.equal(selected.length, 10); assert.equal(unitSelection(selected, unit), 'all');
assert.equal(toggleQuestionUnit(selected, unit).length, 0);
assert.equal(unitSelection([selected[4]], unit), 'partial');
const partial = [{ ...selected[4], score: 7 }];
selected = toggleQuestionUnit(partial, unit);
assert.equal(selected.length, 10); assert.equal(selected[4].score, 7);
assert.deepEqual(selected.map(i => i.question.originalNo), Array.from({ length: 10 }, (_, i) => String(i + 16)));
assert.equal(unitSelection(selected, unit), 'all');
const outdated = [{ ...selected[4], score: 9, question: { ...selected[4].question, material: 'Old passage version' } }];
const completed = toggleQuestionUnit(outdated, unit);
assert.equal(buildPaperUnits(completed).length, 1); assert.equal(completed[4].score, 9);
const singles: PaperItem[] = Array.from({ length: 195 }, (_, i) => ({ question: { ...blankQuestion(), id: `single-${i}`, stem: 'Standalone', originalNo: String(i + 1) }, score: 2 }));
assert.throws(() => toggleQuestionUnit(singles, unit), /200.*整道大题/);
assert.equal(singles.length, 195); // capacity failure is atomic
const mixed = [...singles.slice(0, 1), ...selected, ...singles.slice(1, 2)];
const moved = movePaperUnit(mixed, 1, 1);
assert.deepEqual(buildPaperUnits(moved).map(u => u.items.length), [1, 1, 10]);
assert.deepEqual(moved.slice(2).map(x => x.question.id), selected.map(x => x.question.id));
assert.equal(removePaperUnit(mixed, unit).length, 2);
assert.deepEqual(buildPaperUnits(JSON.parse(JSON.stringify(mixed))).map(u => u.display.map(q => q.stem)), buildPaperUnits(mixed).map(u => u.display.map(q => q.stem)));
const interleaved = [selected[2], singles[0], ...selected.slice(0, 2), ...selected.slice(3)];
assert.deepEqual(buildPaperUnits(interleaved).map(u => u.items.length), [10, 1]);
assert.equal(buildPaperUnits(interleaved)[0].display[0].stem, '第 1 空（见共用材料）');
assert.ok(buildQuestionUnits(questions.slice(0, 1))[0].numberingIssues.length);
const clean = (list: typeof questions) => list.map(q => ({ ...q, images: [], imageLabels: [] }));
const paper: Paper = { id: 'unit-regression', title: '整题选入与内部编号回归', grade: '七年级', minutes: 45,
    items: [...singles.slice(0, 1), ...clean(questions).map(question => ({ question, score: 2 })), ...clean(foreign).map(question => ({ question, score: 3 }))] };
await assert.rejects(() => buildPaperDocument({ ...paper, items: [{ question: { ...questions[0], images: [], imageLabels: [] }, score: 2 }] }, false), /不完整的大题/);
const student = await Packer.toBuffer(await buildPaperDocument(paper, false));
const teacher = await Packer.toBuffer(await buildPaperDocument(paper, true));
const st = (await mammoth.extractRawText({ buffer: student })).value;
const tt = (await mammoth.extractRawText({ buffer: teacher })).value;
assert.match(st, /第 2 大题 · 完形填空/); assert.match(st, /第 3 大题 · 完形填空/);
assert.equal((st.match(/Word 1\._+/g) || []).length, 2);
assert.equal((st.match(/10\.\tA\. first\tB\. second\tC\. third\tD\. fourth/g) || []).length, 2);
assert.match(st, /满分 52 分/); assert.match(st, /共 20 分/); assert.match(st, /共 30 分/);
assert.doesNotMatch(st, /（[23] 分）/);
assert.doesNotMatch(st, /第 16 空|Word 16\._+|参考答案与解析/);
assert.match(tt, /参考答案与解析/);
assert.equal((tt.match(/第 2 大题 · 完形填空/g) || []).length, 2);
assert.equal((tt.match(/10\. B\n/g) || []).length, 2); assert.doesNotMatch(tt, /（[23] 分）/);
assert.equal(JSON.stringify(questions), original);
if (process.argv[2]) {
    const state = JSON.parse(readFileSync(process.argv[2], 'utf8').replace(/^\uFEFF/, '')) as State;
    const real = buildQuestionUnits(state.questions).find(u => u.questions[0].source === 'Unit1检测卷_模板A.docx' && u.questions[0].type === '完形填空');
    assert.ok(real); assert.equal(real.questions.length, 10);
    assert.equal(real.display[0].stem, '第 1 空（见共用材料）');
    assert.equal(real.display[9].stem, '第 10 空（见共用材料）');
    assert.match(real.material, /1\._+/); assert.match(real.material, /10\._+/);
    assert.doesNotMatch(real.material, /(?:16|25)\._+/);
    assert.deepEqual(real.questions.map(q => q.answer), real.display.map(q => q.answer));
    assert.equal(real.sharedImages.length, 1); assert.deepEqual(real.numberingIssues, []);
    assert.equal(toggleQuestionUnit([], real).length, 10);
    console.log('PASS: real Unit1 cloze 16–25 → 1–10, all 10 answers retained, shared image deduplicated.');
}
if (process.argv[3]) { mkdirSync(process.argv[3], { recursive: true }); writeFileSync(process.argv[3] + '/unit-student.docx', student); writeFileSync(process.argv[3] + '/unit-teacher.docx', teacher); }
console.log('PASS: whole-unit filtering/selection, stable source boundaries, local numbering, no numeral corruption, 200-child atomic cap, partial completion, group moves/removal, old snapshots, incomplete-export guard, student/teacher DOCX numbering.');
