import assert from 'node:assert/strict';
import { readFileSync, writeFileSync } from 'node:fs';
import { parseWord } from '../lib/import-docx';

// The user-supplied document is an optional local fixture, never bundled with source releases.
const path = process.argv[2];
if (!path) throw new Error('Usage: real-paper.test <path to Unit1 DOCX> [report JSON path]');
const { source, images } = await parseWord(new Uint8Array(readFileSync(path)), '七年级', 'Unit1检测卷_模板A.docx', 'unit1-test');
const qs = source.questions!;
const q = (n: number) => qs.find(x => x.originalNo === String(n))!;
console.log(JSON.stringify({ report: source.report, types: Object.fromEntries([...new Set(qs.map(q => q.type))].map(t => [t, qs.filter(q => q.type === t).length])), warnings: source.warnings, questions: qs.map(q => ({ no: q.originalNo, type: q.type, options: q.options.length, answer: q.answer.slice(0,100), analysis: q.analysis.length, images: q.imageLabels, warnings: q.warnings })) }, null, 2));
if (process.argv[3]) writeFileSync(process.argv[3], JSON.stringify(source, null, 2));
assert.equal(qs.length, 61);
assert.deepEqual(qs.map(q => q.originalNo), Array.from({length:61}, (_,i) => String(i+1)));
assert.equal(source.report!.matchedAnswers, 61);
assert.deepEqual(source.report!.unmatchedAnswers, []);
assert.deepEqual(source.report!.duplicateNumbers, []);
assert.deepEqual(source.report!.missingNumbers, []);
assert.equal(images.length, 6);
assert.equal(source.report!.imageCount, 6);
assert.equal(qs.filter(x => x.type === '听力选择').length, 15);
assert.equal(qs.filter(x => x.type === '完形填空').length, 10);
assert.equal(qs.filter(x => x.type === '阅读理解').length, 15);
assert.equal(qs.filter(x => x.type === '句子还原').length, 5);
assert.equal(qs.filter(x => x.type === '任务型阅读').length, 5);
assert.equal(qs.filter(x => x.type === '短文填空').length, 10);
assert.equal(qs.filter(x => x.type === '书面表达').length, 1);
for (let n=1;n<=15;n++) assert.equal(q(n).options.length,3);
for (let n=16;n<=40;n++) assert.equal(q(n).options.length,4);
for (let n=41;n<=45;n++) { assert.equal(q(n).options.length,5); assert.equal(q(n).material,q(41).material); }
for (let n=51;n<=60;n++) assert.equal(q(n).material,q(51).material);
assert.match(q(16).material,/16\._{2,}/);
assert.match(q(25).material,/25\._{2,}/);
assert.equal(q(26).material,q(30).material);
assert.notEqual(q(30).material,q(31).material);
assert.notEqual(q(35).material,q(36).material);
assert.deepEqual(q(29).imageLabels,['选项 A 配图','选项 B 配图','选项 C 配图','选项 D 配图']);
assert.ok(q(29).options.every((o,i) => o.includes(`选项 ${'ABCD'[i]} 配图`)));
assert.match(q(50).material,/【画线：/);
assert.match(q(61).stem,/要求：1/);
assert.match(q(61).stem,/2\. 文中应包括/);
assert.match(q(61).stem,/3\. 文中不得出现/);
assert.match(q(61).answer,/My name is Li Hua/);
assert.match(q(61).answer,/What about you\?/);
assert.match(q(16).analysis,/考查名词/);
assert.match(q(49).analysis,/汉语角/);
const choices = ['C','C','C','A','A','C','C','B','A','B','C','B','C','A','B','D','A','C','A','B','A','D','A','D','B','C','D','C','A','D','B','D','A','C','B','B','A','B','D','C','C','D','A','E','B'];
choices.forEach((answer,i) => assert.equal(q(i+1).answer,answer));
assert.deepEqual(qs.slice(50,60).map(x => x.answer),['from','hobbies','the','loves','are','mistakes','His','tofu','about','to make']);
console.log('PASS: real Unit1 document, all 61 numbers/answers, 7 question types, passages, all 6 images with option labels, writing requirements, full model essay and explanations.');
