import assert from 'node:assert/strict';
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { Packer } from 'docx';
import { buildPaperDocument } from '../lib/export-docx';
import type { State } from '../lib/model';
const origin = 'http://127.0.0.1:5173';
const signIn = await fetch(origin + '/signin-with-chatgpt?return_to=/', { redirect: 'manual' });
const cookie = signIn.headers.get('set-cookie')?.split(';')[0];
assert.ok(cookie);
const auth = { Cookie: cookie! };
assert.equal((await fetch(origin + '/api/workspace/state')).status, 401);
assert.equal((await fetch(origin + '/api/workspace/question', { method: 'POST', headers: { ...auth, Origin: 'https://unrelated.example', 'Content-Type': 'application/json' }, body: '{}' })).status, 403);
assert.equal((await fetch(origin + '/api/workspace/question', { method: 'POST', headers: { ...auth, 'Content-Type': 'application/json' }, body: '{}' })).status, 400);
const bad = new FormData();
bad.append('grade', '七年级');
bad.append('file', new Blob(['not a Word file']), 'broken.docx');
assert.ok([400, 413].includes((await fetch(origin + '/api/workspace/import', { method: 'POST', headers: auth, body: bad })).status));
const before = await (await fetch(origin + '/api/workspace/state', { headers: auth })).json() as State;
assert.ok(before.questions.length >= 6);
assert.ok(before.papers.length >= 1);
const source = before.sources.find(s => s.name === '初中英语_Word导入示例.docx');
assert.ok(source);
const original = await fetch(origin + `/api/workspace/source/${source!.id}/file`, { headers: auth });
assert.equal(original.status, 200);
const form = new FormData();
form.append('grade', '七年级');
form.append('file', new Blob([await original.arrayBuffer()]), source!.name);
const duplicate = await (await fetch(origin + '/api/workspace/import', { method: 'POST', headers: auth, body: form })).json() as {
    id: string;
    duplicate: boolean;
    committed: boolean;
};
assert.equal(duplicate.id, source!.id);
assert.equal(duplicate.duplicate, true);
assert.equal(duplicate.committed, true);
const after = await (await fetch(origin + '/api/workspace/state', { headers: auth })).json() as State;
assert.equal(before.questions.length, after.questions.length);
const paper = after.papers.find(p => p.title.includes('测试示例'));
assert.ok(paper);
assert.equal(paper!.items.length, 6);
assert.equal(paper!.items.reduce((n, i) => n + i.score, 0), 20);
const out = process.env.QA_OUTPUT_DIR || '.sites-runtime/qa';
mkdirSync(out, { recursive: true });
writeFileSync(out + '/student.docx', await Packer.toBuffer(await buildPaperDocument(paper!, false)));
writeFileSync(out + '/teacher.docx', await Packer.toBuffer(await buildPaperDocument(paper!, true)));
console.log('PASS: login required, cross-origin blocked, invalid payloads rejected, malformed DOCX rejected, original file download, duplicate upload idempotence, persisted question bank, persisted 20-point paper and generated both DOCX versions.');
